### ISSUE TITLE
Question regarding the sdk

### ISSUE THREAD

**Issue by unbalanced** [ironSource/atom-javascript#15]
Great to see your js sdk guys, few questions:

1. Regarding the "Tracker" object (function). it's name seem too generic name. it's reasonable that a developer already have "Tracker" object under his codebase and it would collide with yours. did you consider using namespace like "IronSourceAtom" for these "classes"? 
e.g. 
```javascript
new IronSourceAtom.Tracker() 
```

2. Almost any popular js sdk nowadays offers developers async loading code snippet
e.g.
```javascript
  window.fbAsyncInit = function() {
    FB.init({
      appId      : 'your-app-id',
      xfbml      : true,
      version    : 'v2.6'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
```
Did you consider offering it?

**Comment by zeevmoney** [comment]
Thanks for the feedback. I agree with both of your ideas.
We will take care of it asap.

**Comment by zeevmoney** [comment]
We added this in version 1.5.0, will be released today.

Thanks!
